### ISSUE TITLE
Any plan on switching to graceful-fs?

### ISSUE THREAD

**Issue by BruceLampson** [lucagrulla/node-tail#108]

**Comment by lucagrulla** [comment]
Hi @BruceLampson 

Any particular reason for suggesting that change?

**Comment by BruceLampson** [comment]
@lucagrulla I'm working on a project that's meant to be cross-platform and requires monitoring several files. I've created a class wrapper that allows me to handle this scenario.  I haven't gotten to testing this on Windows yet. My understanding is that **graceful-fs** is a drop-in replacement for the native **fs** that prevents EMFILE errors from occurring and I was hopping not having to deal with this issue

`const { Tail } = require('../libs/tail');
const EventEmitter = require("events");
export default class Watch extends EventEmitter {
    constructor(files) {
        super();
        this.files = files
        this.watcher = []
        this.files.forEach(file => {
            this.watcher[file] = new Tail(file)
            this.watcher[file].on('line', data => this.emit('buffer', data))
            this.watcher[file].on('error', error => this.emit('error', error))
        })
    }
}
`

const watch = new Watch(['file1.txt', 'file2.txt',...]);

**Comment by lucagrulla** [comment]
Ok.
And you do need to monitor more than 1000 files?

**Comment by BruceLampson** [comment]
@lucagrulla good question, I might not have control over the number of files the client will be monitoring... But I get your point. If this were to be the case (more than 1000 files) perhaps the user should be headed to another direction; tuning up **ulimit** or horizontally scaling.
