### ISSUE TITLE
Rename behaviour

### ISSUE THREAD

**Issue by jawj** [lucagrulla/node-tail#110]
Just been looking at the source while evaluating similar tailing options for node.

On [line 110](https://github.com/lucagrulla/node-tail/blob/7a0e7470c5e686639b043a0fe3b2da87397e8392/src/tail.coffee#L110), handling file renames, is it possible that we'll miss one second's worth of file updates?

Would a possible fix be to always tail from the beginning when switching across (possibly after checking the new file really is shorter than the old)?

Thanks.

**Comment by lucagrulla** [comment]
Fixed in V2.1.0.
