### ISSUE TITLE
From beginning option does not work in release 2.1.0

### ISSUE THREAD

**Issue by pdwinkel** [lucagrulla/node-tail#121]
**new Tail(file, {fromBeginning: true})** does not emit the current lines until a new line is appended to the file.
This did work in release 2.0.4.

Possible problem is that **this.pos** is not initialized. 
Adding the following line to the constructor fixes the problem:
```
this.pos = 0;
```

**Comment by lucagrulla** [comment]
Sorry about this. 
It's now fixed with 2.1.1.
