### ISSUE TITLE
Unit tests failing

### ISSUE THREAD

**Issue by chriskinsman** [lucagrulla/node-tail#144]
I tried to run the unit tests prior to making a pull request and have found that 9 are failing and 5 are passing on MacOS with no changes to the project.

node v14.15.3

Is this a known issue?

**Comment by lucagrulla** [comment]
The test suite fails from time to time for a timeout because it takes slightly longer for the code to execute. I'll try to improve the test suite reliability, but I'll close the issue in the meantime
