### ISSUE TITLE
delete data after read?

### ISSUE THREAD

**Issue by digitalml** [lucagrulla/node-tail#153]
This is a really great library, thank you for making it. 

I'm using this is a named pipe mechanism for two node apps. The first node app streams data into the named pipe and the second node app uses tail to read from it in real time. The problem I'm facing is that the named pipe file is getting very large through the day. Is there a way to have tail remove the line from the named pipe file it's read?

Thanks

**Comment by lucagrulla** [comment]
If it doesn't happen already, no, it's not possible.
I assume that the low-level mechanism used to retrieve content is not flushing the buffer.
