### ISSUE TITLE
No way to catch errors if file do not exists or renamed

### ISSUE THREAD

**Issue by LeoIannacone** [lucagrulla/node-tail#16]
Hi all,

there's no way to catch exception coming from "file not exists" error or "rename" events ?

This test crashes everytime. And I am not able to control exceptions.

```
var Tail = require('tail').Tail
  , exec = require('child_process').exec

exec('echo hello world 0 >> file.txt')

tail = new Tail('file.txt')

tail.on("line", function(data) {
    console.log(data);
});

setTimeout(function() {
  exec('echo hello world 1 >> file.txt')
}, 1000)

setTimeout(function() {
  exec('mv file.txt old.txt')
}, 1500)

setTimeout(function() {
    echo('echo hello world 2 >> file.txt')
}, 3000)
```

It looks like problem comes from:
```
    else if e is 'rename'
      @unwatch()
      setTimeout (=> @watch()), 1000
```
you may need to check if file exists before call @watch ... if it does not exist, call setTimeout and check again.

**Comment by lucagrulla** [comment]
release V1.0.0 is addressing the problem with an extra optional parameter that will disable the tail -F behaviour.
