### ISSUE TITLE
Crashes when using `nLines` with large files

### ISSUE THREAD

**Issue by MrDiggles2** [lucagrulla/node-tail#161]
Hello! Big fan of this library.

I noticed that when using the `nLines` option with larger files (2GB+), the application will crash.

I believe it's due to this bit of code here: https://github.com/lucagrulla/node-tail/blob/master/src/tail.js#L56-L59

I realize this is an edge case; would you open to accepting a PR to account for this?

**Comment by lucagrulla** [comment]
Hello @MrDiggles2,

Thanks for flagging this.
I'll be happy to _consider_ a PR, as much as it's not changing existing behaviours.
