### ISSUE TITLE
Error when file does not exist yet "Error: ENOENT, no such file or directory ..."

### ISSUE THREAD

**Issue by InstanceOfMichael** [lucagrulla/node-tail#32]
```
fs.js:797
  return binding.stat(pathModule._makeLong(path));
                 ^
Error: ENOENT, no such file or directory '../storage/logstash/20151215-fpm-fcgi.log'
    at Error (native)
    at Object.fs.statSync (fs.js:797:18)
    at new Tail (/home/forge/www/client1/logwatch/node_modules/tail/tail.js:67:16)
    at /home/forge/www/client1/logwatch/server.js:32:16
    at Array.forEach (native)
    at Object.<anonymous> (/home/forge/www/client1/logwatch/server.js:30:3)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
```

A. In my use-case scenario I think it would be safe to ``touch`` this file first. I'm a little new to streams and tails. Is that the recommended action?

B. Any advice for tailing a daily log (e.g. opening a new tail every midnight)?

**Comment by shortstuffsushi** [comment]
This would be addressed to some extent by #31.

**Comment by shortstuffsushi** [comment]
FWIW, I'm running up against this same issue and debating the solution. A touch-tail sequence should work just fine for the most part, unless the timestamps on the files are vital.

**Comment by InstanceOfMichael** [comment]
Maybe "touch first" should be an option?

I'm also finding that if I use the ``{ fromBeginning: true }`` option, I need to touch again after if the file is not actively being written to.

**Comment by shortstuffsushi** [comment]
I'm not sure that would make sense for this library, as I don't think that behavior is part of the actual tail tool. I'm not sure about the `fromBeginning`, though I feel like I was seeing similar behavior -- I was expecting to load all the existing lines, but wasn't seeing that happening (it may have just been the way mine was set up, though).

**Comment by lucagrulla** [comment]
I am reviewing the PR #31  in these days but I think that a plain error when the file doesn't exist is a valid behaviour(more than emitting an error actually...there's nothing to tail, I can't see the need of creating the object at all). The library doesn't handle very well log rotation, and this is something that I should address at a certain point(a neat PR is welcome as well).

**Comment by InstanceOfMichael** [comment]
I just use https://www.npmjs.com/package/node-schedule and got the log rotation down it seemed easy. Probably no need for a PR
