### ISSUE TITLE
tail.on('line', function(data)) may get messy data

### ISSUE THREAD

**Issue by sunyonggang** [lucagrulla/node-tail#33]
i use tail to focus on a file,  when i push about 10,000 messages to the file, the function(data) may return a messy message, then i have to handle this exception: 
```
error: SyntaxError: Unexpected token Z
content: Z],用户[2108420],道具ID[54],道具名称[1分钟加速],道具增加[1]."}

the message should be a json like:
content: {"message": "时间[2015-08-14T13:48:37Z],用户[2108420],道具ID[54],道具名称[1分钟加速],道具增加[1]."}
```
I checked this exception happen in tail.on(), so what could i do next? how to fix it?
:racehorse:

**Comment by sunyonggang** [comment]
I'm sorry that my English is not very good.

**Comment by lucagrulla** [comment]
My guess is that the problem is the encoding. tail currently works with utf-8 streams and looking at your example I think you are not using utf-8.

What's the econding of the file you are trying to tail?

**Comment by sunyonggang** [comment]
i checked the file encoding is utf-8，my platform is Mac use node.js 0.10.38.
besides my platform, i tried on ubuntu 14.04 in node.js 0.10.40, it's also crash my service when the data is huge and fast.

**Comment by lucagrulla** [comment]
Regarding the first problem it's very difficult for me to offer an
analysis, I should have access to the file, the number of log lines per
secs etc etc.

My understanding is that the file you are tailing grows in real time. IS
this assumption correct? How many messages are you pushing per second?
Can you run a couple of tests?

1) tail the same file once completed. i.e. take the log, move it away from
the producer that is pushing more lines in and try to tail it. Is it
failing in this scenario?
2)  tail the same file with the same lines pushed into the file but slow
down the producer, i.e.  produce less lines per second.


Cheers,
Luca

**Comment by sunyonggang** [comment]
there is no more about this bug, so I  closed it temporarily :hushed:
