### ISSUE TITLE
Broken on kernels without inotify (fs.watch) support

### ISSUE THREAD

**Issue by JamesBarwell** [lucagrulla/node-tail#36]
Hi, I have encountered a problem using this module on a Linux kernel that does not support inotify, because `fs.watch` does not work without it. The module always uses `fs.watch` if available in the node API, and I am using the node v4 so this is always the case.

This change has come from #7 which states that `fs.watchFile` is deprecated, however this is not true - the [documentation](https://nodejs.org/api/fs.html#fs_fs_watchfile_filename_options_listener) simply states to use `fs.watch` where possible.

> Note: fs.watch() is more efficient than fs.watchFile and fs.unwatchFile. fs.watch should be used instead of fs.watchFile and fs.unwatchFile when possible.

I don't think there's any simple, clean way to test whether `fs.watch` is going to work. At the moment the best solution I can think of would be to allow the user to provide an option/flag to force the use of `fs.watchFile` rather than `fs.watch`.

The [documentation for fs.watch](https://nodejs.org/api/fs.html#fs_fs_watch_filename_options_listener) contains various other caveats around its use so a providing an override would benefit anyone using this module on a system that cannot support its requirements, not just my problem with a lack of inotify support.

Cheers.

**Comment by lucagrulla** [comment]
Hey,

Thanks for this.

There are few bugs/PR on this topic; I'll probably add the flag as you suggested for next release.

**Comment by franck34** [comment]
my best npm for file monitoring is chokidar. A little bit heavy for this module perhaps. Just a suggestion to forget fs.watch vs fs.watchFile problematics (perhaps ?)

**Comment by osallou** [comment]
+1 for getting an option, getting issue at tailing a log file when writing on a different server.
watchFile works nicely in this case.

**Comment by osallou** [comment]
Any news, release plan? This issue is a blocking one for me. I may clone project to fix it in the meanwhile but i d like to avoid managing a temporart only npm module.

**Comment by lucagrulla** [comment]
I might have a window of time towards the end of August, but not guaranteed at this stage.

**Comment by lucagrulla** [comment]
Added option to force watchFile strategy.
