### ISSUE TITLE
Don't write to console

### ISSUE THREAD

**Issue by alexgorbatchev** [lucagrulla/node-tail#38]
A module shouldn't write to console, ever. This is a very bad practice, I encourage to remove all calls to console.

**Comment by martonw** [comment]
+1 to this. Or at least it should be a configurable behavior. Probably the best way to implement such debug logs in a module is the use of `util.debuglog`. See here: https://nodejs.org/api/util.html#util_util_debug_string.

**Comment by lucagrulla** [comment]
Hi,

Thanks for raising the issue.

There are no debug information, there are only info level info about the library being up and running and errors. I do agree that debug info on console are bad practice, I'm not so convinced that having meaningful lifecycle information is a bad practice. 

util.debug is deprecated so it's not helping
I might add a flag to control the behaviour in a future release.

**Comment by alexgorbatchev** [comment]
I think the best way to expose lifecycle is via emitting events and library consumer should be free to choose how to handle that lifecycle.

**Comment by martonw** [comment]
I think if that is a lifecycle info you can use events or callbacks. If that is a trace info about what is going on under the hood, you can use `util.debuglog` which is often used by internal node.js libraries for the same purpose (to clarify, `util.debug` is deprecated, but `util.debuglog` is not. The link with the right anchor: https://nodejs.org/dist/latest-v5.x/docs/api/util.html#util_util_debuglog_section)

**Comment by abesto** [comment]
+1 to events. My use-case: I'd like to add the logs emitted by `node-tail` to my logging system, so that I can track everything that's going on in my app. Currently I have no way of doing that, short of overriding `console.log`.

**Comment by lucagrulla** [comment]
Emitting log details would mean mixing behaviours and I'm not keen(i.e. this is library logging, not an event that clients have to listen to). An approach I'm considering is accepting a "log interface" parameter in the constructor hash. 

Something along the way of:
```javascript
new Tail('myFile.log', {logger: console})
```
As much as that object responds to ```info ```, ```error``` etc it's cool. 
This approach will allow people to inject their preferred logging framework.

**Comment by abesto** [comment]
That'd work for me - it'd be even less work to integrate than with events (which, OTOH, can be considered conceptually cleaner).

**Comment by lucagrulla** [comment]
Closed with release 1.1.0.
