### ISSUE TITLE
Issue with release V1.1.0

### ISSUE THREAD

**Issue by rosscourt** [lucagrulla/node-tail#41]
Hi, I've installed tail@1.1.0 but the optional `logger` parameter functionality seems to be missing from this release.

I've verified my installed version is 1.1.0 by checking the version in `node_modules/tail/package.json` and looked at the JS file `lib/tail.js` which still contains these lines:

    console.info("Tail starting:");
    console.info("filename:", this.filename);
    console.info("options:", options);

Maybe there was an issue with the publish.

**Comment by franck34** [comment]
Same here (extra console.info) @lucagrulla should be quick to fixe and release a new version.

Thanks for this little and efficient module, it fill my needs

**Comment by franck34** [comment]
There is some extra console.error too

`console.error("Tail error:" + error);`

`console.error("'rename' event for " + this.filename + ". File not available.");`

**Comment by lucagrulla** [comment]
First sorry for fixing this just now.;for whatever reason I didn't see the issues notification until today :-(

This should now be fixed. Try 1.1.1 and let me know.
