### ISSUE TITLE
disable output of options

### ISSUE THREAD

**Issue by Pekinese** [lucagrulla/node-tail#42]
How to disable the output of options?

I currently use this code:

`var options= {lineSeparator: /[\r]{0,1}\n/, fromBeginning: false, watchOptions: {}, follow: true}

tail = new Tail("query.log", options);`

This results in:

> Tail starting:
filename: query.log
options: { lineSeparator: /[\r]{0,1}\n/,
  fromBeginning: false,
  watchOptions: {},
  follow: true }

How to disable this output?

**Comment by lucagrulla** [comment]
Which version of the library are you using? 

With the latest version if you don't pass a logger object as part of the configuration you shouldn't see any output.

**Comment by Pekinese** [comment]
I've used npm to install. How to update version of tails now?
