### ISSUE TITLE
feature request: watch directory

### ISSUE THREAD

**Issue by luochen1990** [lucagrulla/node-tail#44]
i.e. I want to watch all ".txt" files under a specified directory

I want to write something like this 

```
tail = new Tail({dir: "~", glob: "*.txt"})
tail.on 'line', (data, file_path) ->
    console.log data, file_path
```

And expecting that the file creating event is automaticly handled and new files that matching the glob option will be auto watched.

**Comment by lucagrulla** [comment]
Hey,

Thanks for the request.
The library does a very well defined job, i.e. mimic tail -f command. It's neat, boundaries are clear, no need to pollute its behaviours with more stuff.


If you need that behaviour it has to be in your client code, i.e. listing the file, attaching one tail bit to each file and keep watching the directory for new file.

Cheers,
Luca
