### ISSUE TITLE
advantages of this library

### ISSUE THREAD

**Issue by ORESoftware** [lucagrulla/node-tail#49]
Hi all, just wondering what the advantages of this library are, over this code:

```js
const cp = require('child_process');

module.exports = function(file){

    const n = cp.spawn('tail',['-f',file]);

    n.on('error', function(err){
        console.error(err.stack || err);
    });

    return n.stdout;
};
```

Please let me know, thanks

**Comment by lucagrulla** [comment]
It works on any platform, not just on *nix or where there's a tail implementation. 

Also if I remember well the child_process package was much less stable and feature rich in 2011(time of the writing of the core of this library) than now.

**Comment by ORESoftware** [comment]
thank you for the info! that totally makes sense
