### ISSUE TITLE
Mangled data in rare conditions

### ISSUE THREAD

**Issue by youurayy** [lucagrulla/node-tail#50]
Possibly related to #22 and #8.

Expected data:
```
{ line1 }
{ line2 }
```

Received data:
```
"" (empty line)
{ line1 }{ line2 }
```

I think this happens due to the asynchronous nature of `fs.ReadStream` used to read the portion of the file:
1. first we get inotify for `{ line1 }`
2. next we get inotify for `\n` which belongs to `{ line1 }`
3. next we get inotify for `{ line2 }\n`

However, the `stream.on 'data'` for 2. executes __before__ the ones for 1. and 3.

This is possible to fix by using `fs.openSync / fs.readSync / fs.closeSync` instead of the asynchronous `fs.ReadStream` API.

**Comment by lucagrulla** [comment]
This should be fixed with release 1.2.4.
