### ISSUE TITLE
Incorrect lines

### ISSUE THREAD

**Issue by megamk** [lucagrulla/node-tail#51]
Hello!
I've already added my comment here lucagrulla/node-tail#8

I'm experiencing this issue when `line` event is receiving corrupted lines from time to time. Initial log file have correct lines. I came across with this in production with log file that gets around 3-5 large lines per second (depending on the time of the day).

To reproduce this I made simple example that can be found here:
https://github.com/megamk/log-tail-emulation

**Comment by alexey-korzhov-clearscale** [comment]
I have the same problem

**Comment by alexey-korzhov-clearscale** [comment]
This problem disappeared when using the option {useWatchFile: true}

**Comment by megamk** [comment]
> This problem disappeared when using the option {useWatchFile: true}

didn't work for me. `useWatchFile` changes the way file changes (rename/move) are handled which is not happening to my file at all

**Comment by Codelica** [comment]
Seeing this also when using fs.watch under Windows.  Using fs.watchFile seems to clear it up but isn't as performant.   Under Linux an Mac OS, fs.watch seems fine.  Maybe related to #50 ?

**Comment by lucagrulla** [comment]
This should not be fixed in release 1.2.4.
