### ISSUE TITLE
Only getting one character

### ISSUE THREAD

**Issue by Zyles** [lucagrulla/node-tail#53]
I want to get this to work but seem unable to.

console.log only outputs the first character of the line first time I update the file.

And the second time a new line is written it writes out thousands of console.logs (for each line)

I tried to use useWatchFile: true and it does not spew out thousands of lines (using Windows). But the "data" is empty.

I am suspecting an encoding issue. Please add option to specify encoding.

**Comment by Zyles** [comment]
Yeah confirmed encoding issue. Add encoding support please. Have to wrap this lib with a encoding converter to work.

**Comment by lucagrulla** [comment]
I add a new parameter to the constructor. Code is pushed to master but not yet released as ver 1.2.2. 

Can you test it for me so we're sure that the fix works? Or at least can you share your file and encoding so I can do a real test?

Thanks,
Luca

**Comment by lucagrulla** [comment]
linked to #48

**Comment by Zyles** [comment]
How do I get the master branch...?

**Comment by lucagrulla** [comment]
...by cloning the repo?

**Comment by Zyles** [comment]
It would be better if you could version it with "-dev" or something so you can pull it with npm.

**Comment by lucagrulla** [comment]
release 1.2.2. it should fix the problem
