### ISSUE TITLE
Tailing a rotating file

### ISSUE THREAD

**Issue by ecdeveloper** [lucagrulla/node-tail#57]
I came across a problem, when watching a log file which rotates once in a while. After the rotation happens (the currently tailed file gets renamed, and a new file with the same name is created) - tail stops getting the updates. 

Looking at the source code, seems like it should take care of it (by capturing the `rename` event). But apparently it just doesn't work for me, and it simply stops tailing the file. I monitor a pm2 log file. 

Are there any workaround to solve that problem?

**Comment by lucagrulla** [comment]
That's weird, as you suggested the scenario is covered in the code.

Which OS are you using?

**Comment by ecdeveloper** [comment]
Ubuntu 16.04.3 LTS. But I suspect it maybe smth funky about how pm2 does the logs rotation.

**Comment by lucagrulla** [comment]
I have no easy way to test pm2 behaviour.
I'll close this for now.
