### ISSUE TITLE
Dynamic pathTofile 

### ISSUE THREAD

**Issue by xtranghero** [lucagrulla/node-tail#58]
May I know how to dynamically adjust the path/log filename? Something like if the log file is dependent on the current system date eventually it changes to following day
_**(i.e: pathfolder/20180314_data_log.txt  ---> pathfolder/20180315_data_log.txt)**_

Any suggestions? Thanks

**Comment by lucagrulla** [comment]
You need to start a new Tail instance with the new file.

**Comment by xtranghero** [comment]
Thanks lucagrulla! So far it works! I haven't yet  tried overnight testing. I used fs.watch to the directory and start another new Tail instance to it.

Is it ok to use tail.on only once?

**Comment by lucagrulla** [comment]
I'm not sure I understand the question.  What do you mean?

**Comment by xtranghero** [comment]
Allow me to share my snip:
```
let pathToLog = '\\\\network\\shared\\p\\a\\t\\h\\moment(Date.now()).format('YYMMDD') + 'data_log.txt';

if(pathToLog){
tail = new Tail(pathToLog);
}

fs.watch(pathToLog, (eventType, filename) => {
   if(`${eventType}` == 'rename'){
      tail = new Tail(pathToLog);
      console.log(tail);
   }
});

tail.on('line', function(data){
   console.log(data);
});

tail.on('error', function(error){
   console.log(error);
});
```

I did an overnight testing, it sees the file has been changed but the tailing stopped. Even if I already created new Tail instance.

**Comment by lucagrulla** [comment]
The moment you create a new Tail instance you have to re-define the listeners.
The library should also deal with 'rename' event correctly. Are you sure you won't have the expected behaviour by simply attaching the library to the first file and then let the library deal with the fule rotation?

**Comment by xtranghero** [comment]
Ohh I see. I will implement that.

> Are you sure you won't have the expected behaviour by simply attaching the library to the first file and then let the library deal with the fule rotation?

That's actually a good question. It opens up my mind. I've revised the code and instead of attaching the library to the first file, I've figured out that I should attached the directory and check the new file exists.
`for(let j=0; j<logFile_obj.ntm.tool_name.length; j++){ // NTM tools
        let gg_log_file = ntm_logFile + logFile_obj.ntm.tool_name[j];
        let pathToLog = gg_log_file + '\\' + moment(Date.now()).format('YYMMDD') + '_CMYK_PPDataLog.txt';

        fs.stat(pathToLog, function(err, stat){ // check if file exists
            if(err == null){ 
                tail = new Tail(pathToLog);

                tail.on('line', function(data){
                    let data_arr = [];
        
                    //** start CLEANING log changes 
                    let line = data.split('\r\n'); // remove \t
                    line.map(function(item){
                        let tabs = item.split('\t');
                        
                        let tab_Nest = tabs[3].split('\r\n'); // remove ;
                        tab_Nest.map(function(item){
                            let nest = item.split(';');
                            //console.log(nest);
            
                            let nest_num = nest[0].split('\r\n'); // remove : @ nest
                            let pressure_num = nest[1].split('\r\n');  // remove : @ pressure
                            nest_num.map(function(item){
                                let nest_val = item.split(':');
                            ////console.log(nest_val[1]);
                                
                                pressure_num.map(function(item){
                                    let pressure_val = item.split(':');
                                    //console.log(pressure_val[1]);
                                    let datetime = moment(new Date(tabs[0] + ' ' + tabs[1])).format();
                                    
                                    data_arr.push(datetime, logFile_obj.ntm.tool_name[j], tabs[2], nest_val[1].replace(/ /g, ''), pressure_val[1].replace(/ /g, ''));
            
                                //console.log(data_arr);
                                    //** end of CLEANING log changes
            
                                    
                                    io.emit(logFile_obj.ntm.tool_name[j] + '_client', data_arr);
                                });
                            });
                        });
                    });
                });
        
                tail.on('error', function(error){
                    console.log(error);
                });
            }
        });
        
        fs.watch(gg_log_file, (eventType, filename) => {
            if(`${eventType}` == 'rename'){

                fs.stat(gg_log_file + '\\' + moment(Date.now()).format('YYMMDD') + '_CMYK_PPDataLog.txt', function(err, stat){
                    if(err == null){
                        tail = new Tail(gg_log_file + '\\' + moment(Date.now()).format('YYMMDD') + '_CMYK_PPDataLog.txt');    
                        //console.log(tail);

                        tail.on('line', function(data){
                            let data_arr = [];
                
                            //** start CLEANING log changes 
                            let line = data.split('\r\n'); // remove \t
                            line.map(function(item){
                                let tabs = item.split('\t');
                                
                                let tab_Nest = tabs[3].split('\r\n'); // remove ;
                                tab_Nest.map(function(item){
                                    let nest = item.split(';');
                                    //console.log(nest);
                    
                                    let nest_num = nest[0].split('\r\n'); // remove : @ nest
                                    let pressure_num = nest[1].split('\r\n');  // remove : @ pressure
                                    nest_num.map(function(item){
                                        let nest_val = item.split(':');
                                    ////console.log(nest_val[1]);
                                        
                                        pressure_num.map(function(item){
                                            let pressure_val = item.split(':');
                                            //console.log(pressure_val[1]);
                                            let datetime = moment(new Date(tabs[0] + ' ' + tabs[1])).format();
                                            
                                            data_arr.push(datetime, logFile_obj.ntm.tool_name[j], tabs[2], nest_val[1].replace(/ /g, ''), pressure_val[1].replace(/ /g, ''));
                    
                                        //console.log(data_arr);
                                            //** end of CLEANING log changes
                    
                                            
                                            io.emit(logFile_obj.ntm.tool_name[j] + '_client', data_arr);
                                        });
                                    });
                                });
                            });
                        });
                
                        tail.on('error', function(error){
                            console.log(error);
                        });
                    } else {
                        console.log(gg_log_file + '\\' + moment(Date.now()).format('YYMMDD') + '_CMYK_PPDataLog.txt is missing');
                    }
                });
                
            }
        });
        
    }`

Now I'll test it overnight. :)

**Comment by xtranghero** [comment]
Thanks Luca for the ideas. It's now working.
