### ISSUE TITLE
Tailing file stop updating after a while

### ISSUE THREAD

**Issue by ExDomino** [lucagrulla/node-tail#59]
Hello,

I'm trying to tail a file to monitor its changes, but after a while, the monitoring stops by itself. Other programs like "Notepad++" successfuls to monitor the changes and it's only when those other programs detect a change in the file that Tail "unsleeps" and detect it as well.

In short, if I monitor a file, at the begening it works perfectly well, but after a while, Tail only detect a change when the file is open by another program OR if another program checks if the file has changed.

What could cause this problem?
Thank you in advance!

**Comment by lucagrulla** [comment]
I'm confused. 
Notepad is an editor, not a library to tail file. How is this related to the use case?

Are you sure the file has new line appended when you don't see changes?

**Comment by ExDomino** [comment]
If I open my file with Notepad++ then minimize it in the taskbar and maximize it after the file has changed, it shows a dialogbox to say that the file has changed and if I want to reload it. Exactly at the same time that I see this dialogbox from Notepad++ appear, my program (that use your Tails api) detect the change. At the very exact milisecond, like if Notepad++ unsleeped it. If I configure Tail to use watchFile instead, the change are monitored correctly but it's a bit slow (each 5 sec I think) but it works.

**Comment by lucagrulla** [comment]
Watch relies on the underlying operating system. If the OS is not effective then the library might miss events. 
It looks like the combination of Windows and network drive make it not effective. watchFile will just do polling(no OS integration) but is la bit ess performant.

**Comment by ExDomino** [comment]
watch() doesn't work at all on my desktop computer with tailed files on C: drive that is a SSD.
If I set useWatchFile() instead, it works perfectly well but it's slow and I need to read changes as fast as I can.

I think the problem come with Windows 7 that doesn't support Tails at all. I don't know how to fix the problem. Do you have any solution?

**Comment by lucagrulla** [comment]
Great.
As stated before watch relies on the underline OS behaviour. 
If Win7 has limitations in this area then the library won't act as expected. 
https://nodejs.org/api/fs.html#fs_caveats

**Comment by lucagrulla** [comment]
Given is related to known limitations of the underline NodeJS implementation on Windows I'll close this.
