### ISSUE TITLE
75% of lines being dropped during fast large file updates

### ISSUE THREAD

**Issue by dustinbolton** [lucagrulla/node-tail#60]
I am attempting to tail a very fast log files (100+ lines/sec). I'm having a problem where 75% of lines are being dropped when using watch.  When using watchFile about 5% of lines are dropped. It seems this library has a bug with very fast updates.  There are some other related issues open as well regarding this.  I'd love to see this bug fixed.

The following library seems to handle this situation without dropping any lines if it helps:
https://github.com/Juul/tail-stream

**Comment by lucagrulla** [comment]
Next release (hoepfully within the next weeks) should have this problem fixed.

**Comment by lucagrulla** [comment]
This shoiuld be fixed with version 1.2.4.
