### ISSUE TITLE
Initial `fs.statSync` errors can't be handled

### ISSUE THREAD

**Issue by wearhere** [lucagrulla/node-tail#66]
If the file to-be-tailed doesn't exist, [this](https://github.com/lucagrulla/node-tail/blob/e3d2adcc905563beca32afcef03786dc1fc08610/src/tail.coffee#L50) will error, but that error can't be handled because `watch` is called from within the constructor, before the client's had a chance to register an `'error'` event handler.

I'd be glad to put up a PR to fix this but I'm not sure what fix you'd prefer. My inclination is to call `watch` asynchronously (i.e. change [this](https://github.com/lucagrulla/node-tail/blob/e3d2adcc905563beca32afcef03786dc1fc08610/src/tail.coffee#L44) to `process.nextTick(=> @watch(pos))`, except for that that'll break the tests since they expect `node-tail` to catch [synchronous writes](https://github.com/lucagrulla/node-tail/blob/e3d2adcc905563beca32afcef03786dc1fc08610/test/tail.coffee#L38) (which is easy enough to change except for that maybe that signals that such a change would break some client code too).

Alternatively we could have `watch` `throw` that `fs.statSync` error rather than `emit` it, except for that that's inconsistent with other error handling in the module and we'd have to change [this](https://github.com/lucagrulla/node-tail/blob/e3d2adcc905563beca32afcef03786dc1fc08610/src/tail.coffee#L85) to handle that change somehow.

**Comment by wearhere** [comment]
A workaround is to have client code call `fs.statSync` on the file before initializing `Tail`.

**Comment by lucagrulla** [comment]
Thanks for this bug report. 
If the file to be tailed is not there the `Tail` has no reason to be initialised, therefore it's probably correct to fail initialization with an exception. There nothing the library can't do about that, it's up to the calling code to figure out why the file is missing and then eventually try to reinitialize Tail.

I'm therefore thinking about removing the unneeded error [emit](https://github.com/lucagrulla/node-tail/blob/e3d2adcc905563beca32afcef03786dc1fc08610/src/tail.coffee#L50) and make explicit that the constructor will throw an exception if the given file is not available.

Thoughts?

**Comment by jarruda** [comment]
How about adding an option to not automatically start watching the file on construction, and wait for an explicit call to `watch`?

**Comment by lucagrulla** [comment]
That approach won't solve the problem; the file might still be missing and the library would fail in the scenario where there's the automatic start.

I started  working on a solution that is based on my previous comment, but not ready yet.

**Comment by lucagrulla** [comment]
Fixed with release 2.0.3.
If the file does not exist the constructor won't initialize the library and an exception will be thrown.
