### ISSUE TITLE
how to tail cross day log file

### ISSUE THREAD

**Issue by sunweiconfidence** [lucagrulla/node-tail#74]
i have a log.txt file with a prefix date, i want to use node.js to monitor the log.txt file changed line in real time, how to set parameter or other method to tail the 2018-09-15-log.txt file? everyday i only want to tail the current day's log file, thanks

**Comment by lucagrulla** [comment]
Hi,

Look at the cofiguration part of the README for an example:

https://github.com/lucagrulla/node-tail#configuration

**Comment by sunweiconfidence** [comment]
but my log file name is changed, so your node-tail configuration is not support now i think, your configuration only support time seperator, tail file name is changing every day, now i intend to use setInterval function to deal with it, any good method to deal with it? thanks
for example:
tail = new Tail("2018-09-17-log.txt");
tail = new Tail("2018-09-18-log.txt");
tail = new Tail("2018-09-19-log.txt");

**Comment by lucagrulla** [comment]
If the file name is chaging then the client code has to deal with it. 
The library handles file rotation accordignly.

**Comment by sunweiconfidence** [comment]
ok, thank you very much
