### ISSUE TITLE
How to handle binary file ?

### ISSUE THREAD

**Issue by dceejay** [lucagrulla/node-tail#75]
How do you configure this to tail a binary file ?

I have a process that appends chunks of binary characters to a file. I can't use a separator to split them as that would remove the split char (and indeed any char I choose as a separator may be present elsewhere in the chunk).  Ideally I just want the new chunk passed through as-is, and preferably as a Buffer, not a string. Is this possible ? 

Or maybe an option to always send the last chunk on close ? That way I could (hopefully) set a separator that would never match, and on close it would send what was the remaining buffer.

**Comment by lucagrulla** [comment]
The library purpose is to tail text files, currently probabvly won't work for a binary file for the reason you explained above. You could try to pass '' as a separator and see if that by chance will help you.

**Comment by lucagrulla** [comment]
I see.
I'll look into this next time I work on the library, but I don't have a timeline.

A good PR that solves both problems (handling the last character properly _and_ accepting '' as a separator) would be welcome :-)

**Comment by dceejay** [comment]
Well it does already accept '' as a separator... it just doesn't handle the last char. And also doesn't accept "no" separator - i.e always send the whole new chunk. For that I'd propose accepting null (the javascript null object) as the separator. Happy to look at doing this as 2 PR so you can check the working as we go.

For first I'd propose an extra option - I'll call it flushAtEOF - but feel free to change of course. If set true it would flush any remaining buffer on close of the input stream - ie the last character if no separator follows it.

For second look for separator of null and then don't try to split - just send the chunk of data.

**Comment by lucagrulla** [comment]
Resolved with release 1.4.0
