### ISSUE TITLE
Incorrect lines returned

### ISSUE THREAD

**Issue by hmeerlo** [lucagrulla/node-tail#8]
I'm using node-tail to tail my access logs which have a high update frequency. But under this load node-tail reports many incorrect lines that start at the middel of the actual line. Any idea what causes this?

**Comment by megamk** [comment]
I'm getting this error with version `1.2.1` under linux. My log file gets about 3 lines per second, and sometimes `line` event receives first half of one line and next line as a one line.  Node version is `4.3.1` and  tail version is `1.2.1`.  Let me know what additional  info might help you.
