### ISSUE TITLE
Always on?

### ISSUE THREAD

**Issue by fmarzocca** [lucagrulla/node-tail#87]
I am using tail on a nodejs express server, to continuosly watch at a log file. Every time a line is added, I send a socket event to the browser client to add the line to a div.

Is there any resource/memory problem in leaving tail always on?

Thanks.

**Comment by lucagrulla** [comment]
The only memory concern you could encounter is if the log file grows much faster than what the library could consume. 
That depends on underline OS, CPU, disk etc so hard to clearly define.

Otherwise no memory leaks are expected.

**Comment by fmarzocca** [comment]
Thanks. My concern could be that I am not closing the “watch” . Has the close function a callback?

**Comment by lucagrulla** [comment]
If the goal is to continuously tail the file then "closign the watch" is not an option.
If instead you do want to explicitly stop wathing the file then you can call "unwatch".

Please read the README documentation:
https://github.com/lucagrulla/node-tail

for more details

**Comment by fmarzocca** [comment]
Sorry, I wasn't clear, my fault. I mean, if the server crashes and then
restarts (it is monitored by forever), could it cause a leak not having
unwatched the tail?


- Sent from my mobile phone. Sorry for typos -

Il mar 11 giu 2019, 17:19 Luca Grulla <notifications@github.com> ha scritto:

**Comment by lucagrulla** [comment]
I'm not sure to which server you are referring to in this scenario. What is going to crash?

If your NodeJS process crashes then all the code running on it dies, including tail library.
If the server where the tailed file exist crashes then you most likely have an exception on your client nodeJS code, causing the library to exit.

**Comment by fmarzocca** [comment]
Clear.
Thank you very much.


- Sent from my mobile phone. Sorry for typos -

Il mar 11 giu 2019, 18:10 Luca Grulla <notifications@github.com> ha scritto:
