### ISSUE TITLE
The tail.on("line", function(data) is not called when tail points to a file sitting on a NFS fs

### ISSUE THREAD

**Issue by trippah** [lucagrulla/node-tail#95]
I have 2 tail objects, 1 pointing to a text file on a local drive and another pointing to a text file sitting on a NFS filesystem.

The first tail (local drive) calls the tail.on() event but the second tail (on nfs) does not call tail.on()

any suggestions or a workaround?

**Comment by lucagrulla** [comment]
the fact you don't receive data from the NFS file is suggesting that NodeJS File module is not working well on NFS. Unfortunately `tail` can't do much if nodeJS doesn't behave as expected.

The only suggestionI have is to try with the`useWatchFile` flag. It will force `tail` to use a different core mechanism, potentially with better low level support for NFS (to be tested).

**Comment by trippah** [comment]
Thank you very much this seems to be working fine
